package:
  name: sample_python_pyspark_analytic
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.1') }}
build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: python setup.py install
source:
  git_url: https://github.build.ge.com/204003354/pyspark_sample.git
requirements:
  build:
    - python 2.7.12
    - setuptools
  run:
    - python 2.7.12
    - pyspark 2.1.0
    - pandas 0.19.2
    - numpy 1.11.2
    - scikit-learn
    - scipy
    - statsmodels
about:
  license: GE Proprietary