package:
  name: sample_python_pyspark_analytic
  version: {{ environ.get('GIT_DESCRIBE_TAG', '0.1') }}
build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  script: python setup.py install
source:
  git_url: https://github.com/YDD9/testTodelete.git
requirements:
  build:
    - python 2.7.12
    - setuptools
  run:
    - python 2.7.12
    - numpy 1.11.2

about:
  license: GE Proprietary